crossover_rate: 0.1
fitness_weights:
- 1
- 1
fitness_weigths:
- 1
- 1
mutation_rate: 0.1
num_elite_groups: 1
num_elite_individuals: 1
num_generations: 25
num_threads: 1
population_size: 100
selection_method: sus
