carrying_capacity: 2000
crossover_methods:
- graph_based_crossover
fitness_functions:
- calculate_qed
mutation_methods:
- hydroxylate_mutate
num_generations: 1000
population_size: 1000
selection_method: stochastic_universal_sampling
