carrying_capacity: 2000
crossover_methods:
- graph_based_crossover
mutation_methods:
- hydroxylation
- atomic_substitution
- methylation
- amination
- fluorination
- carboxylation
num_generations: 1000
population_size: 1000
selection_method: stochastic_universal_sampling
